# Use an official Go image as the base
FROM golang:alpine

# Install Python
RUN apk add --no-cache python3

# Set the working directory to /app
WORKDIR /app

# Copy the Go mod file
COPY go.mod ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the executable
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Expose the ports for incoming connections
EXPOSE 8080 6000

# Run the executable when the container starts
CMD ["./main", "MINER"]